FROM python:3.9-slim AS backend

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py /app/
COPY config.yaml /app/

EXPOSE 3000

CMD ["python", "app.py"]